<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <artifactId>r-uu.app.pragma.bean</artifactId>
  <name>${project.artifactId}</name>
  <description>plain Java bean implementation of Task for pragma</description>

  <parent>
    <groupId>r-uu</groupId>
    <artifactId>r-uu.app.pragma</artifactId>
    <version>0.0.1</version>
  </parent>

  <dependencies>
    <dependency>
      <groupId>r-uu</groupId>
      <artifactId>r-uu.app.pragma.core</artifactId>
    </dependency>
    <dependency>
      <groupId>r-uu</groupId>
      <artifactId>r-uu.app.pragma.backend.dto</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jspecify</groupId>
      <artifactId>jspecify</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <executions>
          <execution>
            <id>default-testCompile</id>
            <phase>test-compile</phase>
            <goals><goal>testCompile</goal></goals>
            <configuration>
              <testExcludes>
                <testExclude>**/module-info.java</testExclude>
              </testExcludes>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
