package de.ruu.lib.fx.comp.demo.hierarchy.sub1;

import de.ruu.lib.fx.comp.FXCAppRunner;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;

/**
 * Java FX Component Application Runner {@link HierarchyDemoSub1AppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2024.05.17 12:57:18:218
 */
public class HierarchyDemoSub1AppRunner extends FXCAppRunner
{
	private static final Logger log = LogManager.getLogger(HierarchyDemoSub1AppRunner.class);

	public static void main(String[] args)
	{
		log.debug("starting HierarchyDemoSub1AppRunner.class.getName()");
		FXCAppRunner.run(HierarchyDemoSub1App.class, args);
		log.debug("finished HierarchyDemoSub1AppRunner.class.getName()");
	}
}