<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <artifactId>r-uu.java</artifactId>
  <name>${project.artifactId}</name>
  <packaging>pom</packaging>
  <description>root aggregator for all r-uu Java projects (lib + app)</description>

  <parent>
    <groupId>r-uu</groupId>
    <artifactId>r-uu.lib.bom</artifactId>
    <version>0.0.1</version>
    <relativePath>lib/bom/pom.xml</relativePath>
  </parent>

  <modules>
    <module>lib</module>
    <module>app</module>
  </modules>

</project>
