package de.ruu.lib.fx.comp.demo.hierarchy.sub2;

import de.ruu.lib.fx.comp.DefaultFXCView;
import jakarta.enterprise.context.Dependent;

/**
 * Java FX Component {@link HierarchyDemoSub2}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2024.05.17 12:57:18:219
 */
@Dependent
public class HierarchyDemoSub2 extends DefaultFXCView
{
}