package de.ruu.lib.fx.comp.demo.hierarchy.sub2;

import de.ruu.lib.fx.comp.FXCAppRunner;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;

/**
 * Java FX Component Application Runner {@link HierarchyDemoSub2AppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2024.05.17 12:57:18:233
 */
public class HierarchyDemoSub2AppRunner extends FXCAppRunner
{
	private static final Logger log = LogManager.getLogger(HierarchyDemoSub2AppRunner.class);

	public static void main(String[] args)
	{
		log.debug("starting HierarchyDemoSub2AppRunner.class.getName()");
		FXCAppRunner.run(HierarchyDemoSub2App.class, args);
		log.debug("finished HierarchyDemoSub2AppRunner.class.getName()");
	}
}