#Writable config
#Profile for Postgres ToolBox / DB edit against Keycloak DB
postgres.backup.database=keycloak
postgres.backup.directory=/home/r-uu/develop/github/java/app/pragma/dbbackup
postgres.backup.executable=/usr/bin/pg_dump
postgres.backup.host=localhost
postgres.backup.password=keycloak
postgres.backup.port=5432
postgres.backup.username=keycloak
postgres.restore.database=keycloak
postgres.restore.executable=/usr/bin/pg_restore
postgres.restore.file=/home/r-uu/develop/github/java/app/pragma/dbbackup/2026.07.05-10.37-keycloak-empty.pg-dump
postgres.restore.host=localhost
postgres.restore.password=keycloak
postgres.restore.port=5432
postgres.restore.username=keycloak
