package de.ruu.lib.postgres.toolbox.ui;

import de.ruu.lib.fx.comp.DefaultFXCView;
import jakarta.enterprise.context.Dependent;

/**
 * Java FX Component {@link PostgresUtilUI}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2025.12.21 09:57:08:095
 */
@Dependent
public class PostgresBackupUI
		extends DefaultFXCView<PostgresBackupUI, PostgresBackupUIService, PostgresBackupUIController>
		implements PostgresBackupUIService
{
}
