pragma.rest-api.scheme=http
pragma.rest-api.host=localhost
pragma.rest-api.port=9090
pragma.postgres.host=localhost
pragma.postgres.port=5432
pragma.postgres.database=pragma
pragma.postgres.username=pragma
pragma.postgres.password=pragma
pragma.postgres.backup.executable=/usr/bin/pg_dump
pragma.postgres.restore.executable=/usr/bin/pg_restore
pragma.postgres.psql.executable=/usr/bin/psql
pragma.auth.test-mode=true
pragma.keycloak.server-url=http://localhost:8080
pragma.keycloak.realm=pragma-realm
pragma.keycloak.client-id=pragma-frontend
pragma.keycloak.username=r-uu
pragma.keycloak.password=r-uu
pragma.keycloak.admin.username=admin
pragma.keycloak.admin.password=admin
pragma.setup.force=true