pragma.rest-api.scheme=http
pragma.rest-api.host=localhost
pragma.rest-api.port=9090
pragma.auth.test-mode=true
pragma.keycloak.server-url=http://localhost:8080
pragma.keycloak.realm=pragma-realm
pragma.keycloak.client-id=pragma-frontend
pragma.keycloak.username=r-uu
pragma.keycloak.password=r-uu
