package de.ruu.lib.fx.demo.comp.main;

import de.ruu.lib.fx.comp.DefaultFXCView;
import jakarta.enterprise.context.Dependent;

/**
 * Java FX Component {@link RUUFXDemoComponentMain}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2024.05.20 14:28:47:925
 */
@Dependent
public class RUUFXDemoComponentMain extends DefaultFXCView<RUUFXDemoComponentMain, RUUFXDemoComponentMainService, RUUFXDemoComponentMainController> { }