package de.ruu.lib.fx.demo.comp.main;

import de.ruu.lib.fx.comp.FXCAppRunner;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;

/**
 * Java FX Component Application Runner {@link RUUFXDemoComponentMainAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2024.05.20 14:28:47:962
 */
public class RUUFXDemoComponentMainAppRunner extends FXCAppRunner
{
	private static final Logger log = LogManager.getLogger(RUUFXDemoComponentMainAppRunner.class);

	public static void main(String[] args)
	{
		log.debug("starting RUUFXDemoComponentMainAppRunner.class.getName()");
		FXCAppRunner.run(RUUFXDemoComponentMainApp.class, args);
		log.debug("finished RUUFXDemoComponentMainAppRunner.class.getName()");
	}
}