#Writable config
#Sun Jul 05 11:49:35 CEST 2026
postgres.backup.database=pragma
postgres.backup.directory=/home/r-uu/develop/github/app-pragma-java/dbbackup
postgres.backup.executable=/usr/bin/pg_dump
postgres.backup.host=localhost
postgres.backup.password=r-uu
postgres.backup.port=5432
postgres.backup.username=admin-postgres
postgres.restore.database=pragma
postgres.restore.executable=/usr/bin/pg_restore
postgres.restore.file=/home/r-uu/develop/github/app-pragma-java/dbbackup/2026.07.05-10.37-pragma-empty.pg-dump
postgres.restore.host=localhost
postgres.restore.password=r-uu
postgres.restore.port=5432
postgres.restore.username=admin-postgres
